package setup

import (
	"bufio"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"runtime"
	"strings"

	"ebupot-app/config"
)

const banner = `
+======================================================+
|                                                      |
|     e-Bupot Portal — Setup Wizard                    |
|                                                      |
|     Konfigurasi pertama kali menjalankan aplikasi    |
|                                                      |
+======================================================+
`

// RunWizard menjalankan wizard instalasi interaktif saat .env belum ada.
// Mengembalikan config yang sudah dimuat dari .env yang baru dibuat.
func RunWizard(yamlData []byte) *config.Config {
	reader := bufio.NewReader(os.Stdin)

	fmt.Print(banner)
	fmt.Println("File konfigurasi (.env) belum ditemukan.")
	fmt.Println("Mari kita setup aplikasi ini.")

	// --- Tanya konfigurasi ---
	port := askInput(reader, "[1] Port aplikasi", "8080")
	domain := askInput(reader, "[2] Domain publik (untuk QR & Share Link)", "localhost:"+port)
	scheme := askInput(reader, "[3] Scheme (http/https/kosong=auto-detect)", "")
	maxUpload := askInput(reader, "[4] Maksimal upload (MB)", "100")

	genSecret := askYesNo(reader, "[5] Auto-generate session secret?", true)
	var secret string
	if genSecret {
		secret = generateSecret()
		fmt.Printf("    Secret dibuat: %s\n\n", secret)
	} else {
		secret = askInput(reader, "    Masukkan session secret manual", generateSecret())
	}

	// --- Buat .env ---
	fmt.Println("--- Membuat konfigurasi ---")
	envContent := buildEnvContent(port, domain, scheme, maxUpload, secret)
	if err := os.WriteFile(".env", []byte(envContent), 0600); err != nil {
		fmt.Printf("  [GAGAL] Tidak bisa membuat .env: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("  [OK] File .env dibuat")

	// --- Buat folder ---
	if err := os.MkdirAll("data", 0755); err != nil {
		fmt.Printf("  [GAGAL] Tidak bisa buat folder data/: %v\n", err)
	}
	fmt.Println("  [OK] Folder data/ dibuat")

	if err := os.MkdirAll("uploads/ebupots", 0755); err != nil {
		fmt.Printf("  [GAGAL] Tidak bisa buat folder uploads/: %v\n", err)
	}
	fmt.Println("  [OK] Folder uploads/ dibuat")

	// --- Setup systemd & Nginx (hanya di Linux + root) ---
	isLinux := runtime.GOOS == "linux"
	isRoot := isRoot()

	if isLinux {
		fmt.Println()

		// Systemd
		if askYesNo(reader, "Setup systemd service (auto-start saat boot)?", isRoot) {
			setupSystemd(reader, port)
		}

		// Nginx
		if askYesNo(reader, "Setup Nginx reverse proxy?", isRoot) {
			nginxDomain := askInput(reader, "  Domain untuk Nginx", domain)
			setupNginx(reader, nginxDomain, maxUpload)
		}

		// SSL
		if askYesNo(reader, "Setup SSL (Let's Encrypt)?", false) {
			sslDomain := askInput(reader, "  Domain untuk SSL", domain)
			setupSSL(reader, sslDomain)
		}
	} else {
		fmt.Println("\n  (Setup systemd/Nginx dilewati — bukan Linux)")
	}

	// --- Selesai ---
	fmt.Println()
	fmt.Println("+======================================================+")
	fmt.Println("|              SETUP SELESAI!                          |")
	fmt.Println("+======================================================+")
	fmt.Printf("|  Aplikasi : e-Bupot Portal                          |\n")
	fmt.Printf("|  Port     : %s\n", port)
	fmt.Printf("|  Domain   : %s\n", domain)
	if scheme != "" {
		fmt.Printf("|  Scheme   : %s\n", scheme)
	} else {
		fmt.Printf("|  Scheme   : auto-detect\n")
	}
	fmt.Printf("|  .env     : %s\n", absPath(".env"))
	fmt.Println("+======================================================+")
	fmt.Println()

	// --- Muat config dari .env yang baru ---
	return config.Load(yamlData)
}

func buildEnvContent(port, domain, scheme, maxUpload, secret string) string {
	return fmt.Sprintf(`# e-Bupot Portal — Generated by Setup Wizard
APP_ENV=production
SERVER_HOST=0.0.0.0
SERVER_PORT=%s
SERVER_DOMAIN=%s
SERVER_SCHEME=%s
DB_PATH=data/ebupot.db
UPLOAD_MAX_SIZE_MB=%s
QR_RECOVERY_LEVEL=high
QR_SIZE=512
SESSION_SECRET=%s
SESSION_MAX_AGE=86400
`, port, domain, scheme, maxUpload, secret)
}

func generateSecret() string {
	b := make([]byte, 32)
	rand.Read(b)
	return hex.EncodeToString(b)
}

func isRoot() bool {
	u, err := user.Current()
	if err != nil {
		return false
	}
	return u.Uid == "0"
}

func absPath(p string) string {
	abs, err := filepath.Abs(p)
	if err != nil {
		return p
	}
	return abs
}

// --- Helper input ---

func askInput(reader *bufio.Reader, prompt, def string) string {
	if def != "" {
		fmt.Printf("%s [%s]: ", prompt, def)
	} else {
		fmt.Printf("%s: ", prompt)
	}
	input, _ := reader.ReadString('\n')
	input = strings.TrimSpace(input)
	if input == "" {
		return def
	}
	return input
}

func askYesNo(reader *bufio.Reader, prompt string, defaultYes bool) bool {
	suffix := "[Y/n]"
	if !defaultYes {
		suffix = "[y/N]"
	}
	fmt.Printf("%s %s: ", prompt, suffix)
	input, _ := reader.ReadString('\n')
	input = strings.TrimSpace(strings.ToLower(input))
	if input == "" {
		return defaultYes
	}
	return input == "y" || input == "yes"
}

// --- Systemd setup ---

func setupSystemd(reader *bufio.Reader, port string) {
	wd, _ := os.Getwd()
	exePath, _ := os.Executable()
	if exePath == "" {
		exePath = filepath.Join(wd, "ebupot-app")
	}

	currentUser := "www-data"
	if u, err := user.Current(); err == nil && u.Uid != "0" {
		currentUser = u.Username
	}

	serviceContent := fmt.Sprintf(`[Unit]
Description=e-Bupot Portal & QR Generator
After=network.target

[Service]
Type=simple
User=%s
Group=%s
WorkingDirectory=%s
ExecStart=%s
EnvironmentFile=%s/.env
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=ebupot
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=%s/data %s/uploads

[Install]
WantedBy=multi-user.target
`, currentUser, currentUser, wd, exePath, wd, wd, wd)

	tmpFile := "/tmp/ebupot.service"
	os.WriteFile(tmpFile, []byte(serviceContent), 0644)

	steps := [][]string{
		{"sudo", "cp", tmpFile, "/etc/systemd/system/ebupot.service"},
		{"sudo", "systemctl", "daemon-reload"},
		{"sudo", "systemctl", "enable", "ebupot"},
	}

	for _, cmd := range steps {
		if !runCmd(cmd[0], cmd[1:]...) {
			fmt.Printf("  [GAGAL] Setup systemd di step: %s\n", strings.Join(cmd, " "))
			fmt.Println("  Lakukan manual atau jalankan sebagai root/sudo")
			return
		}
	}
	fmt.Println("  [OK] Systemd service terpasang (auto-start saat boot)")
	fmt.Println("       Mulai: sudo systemctl start ebupot")
	fmt.Println("       Log  : sudo journalctl -u ebupot -f")
}

// --- Nginx setup ---

func setupNginx(reader *bufio.Reader, domain, maxUpload string) {
	nginxConf := fmt.Sprintf(`server {
    listen 80;
    server_name %s;
    client_max_body_size %sM;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }
}
`, domain, maxUpload)

	tmpFile := "/tmp/ebupot-nginx"
	os.WriteFile(tmpFile, []byte(nginxConf), 0644)

	// Install nginx jika belum ada
	if _, err := exec.LookPath("nginx"); err != nil {
		fmt.Println("  Installing nginx...")
		if !runCmd("sudo", "apt", "install", "-y", "-qq", "nginx") {
			fmt.Println("  [GAGAL] Tidak bisa install nginx")
			return
		}
	}

	sitesDir := "/etc/nginx/sites-available"
	steps := [][]string{
		{"sudo", "cp", tmpFile, sitesDir + "/ebupot"},
		{"sudo", "ln", "-sf", sitesDir + "/ebupot", "/etc/nginx/sites-enabled/ebupot"},
		{"sudo", "rm", "-f", "/etc/nginx/sites-enabled/default"},
		{"sudo", "nginx", "-t"},
		{"sudo", "systemctl", "reload", "nginx"},
	}

	for _, cmd := range steps {
		if !runCmd(cmd[0], cmd[1:]...) {
			fmt.Printf("  [GAGAL] Nginx setup di step: %s\n", strings.Join(cmd, " "))
			return
		}
	}
	fmt.Println("  [OK] Nginx reverse proxy terpasang untuk " + domain)
}

// --- SSL setup ---

func setupSSL(reader *bufio.Reader, domain string) {
	// Install certbot jika belum ada
	if _, err := exec.LookPath("certbot"); err != nil {
		fmt.Println("  Installing certbot...")
		if !runCmd("sudo", "apt", "install", "-y", "-qq", "certbot", "python3-certbot-nginx") {
			fmt.Println("  [GAGAL] Tidak bisa install certbot")
			fmt.Println("  Install manual: sudo apt install certbot python3-certbot-nginx")
			return
		}
	}

	fmt.Printf("  Menjalankan certbot untuk %s...\n", domain)
	fmt.Println("  (Jawab prompt email & agree terms)")
	if !runCmd("sudo", "certbot", "--nginx", "-d", domain, "--redirect") {
		fmt.Println("  [GAGAL] Certbot gagal. Pastikan:")
		fmt.Println("    - DNS domain sudah mengarah ke IP server ini")
		fmt.Println("    - Port 80 & 443 terbuka")
		fmt.Println("  Jalankan manual: sudo certbot --nginx -d " + domain)
		return
	}
	fmt.Println("  [OK] SSL Let's Encrypt terpasang untuk " + domain)
}

// --- Command runner ---

func runCmd(name string, args ...string) bool {
	cmd := exec.Command(name, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	return cmd.Run() == nil
}
